"""Apply checked ShellCheck and tag-safety fixes to the pinned dist template."""

from pathlib import Path
import subprocess
import sys

MAX_WORKFLOW_BYTES = 64 * 1024


def replace_once(text: str, before: str, after: str) -> str:
    if text.count(before) != 1:
        raise ValueError("Pinned dist template changed; review the normalization")
    return text.replace(before, after, 1)


def normalize_shell(text: str) -> str:
    text = replace_once(
        text,
        "# This file was autogenerated by dist:",
        "# ShellCheck and tag-safety fixes: run ci/normalize_dist_workflow.py after dist generate.\n"
        "# This file was autogenerated by dist:",
    )
    text = replace_once(text, '>> $GITHUB_PATH', '>> "$GITHUB_PATH"')
    text = replace_once(text, '> $RUNNER_TEMP/notes.txt', '> "$RUNNER_TEMP/notes.txt"')
    text = replace_once(
        text,
        '          gh release create ',
        '          prerelease_args=()\n'
        '          if [ -n "$PRERELEASE_FLAG" ]; then prerelease_args+=("$PRERELEASE_FLAG"); fi\n'
        '          gh release create ',
    )
    text = replace_once(text, ' $PRERELEASE_FLAG --title', ' "${prerelease_args[@]}" --title')
    text = replace_once(
        text,
        r'name=$(echo "$filename" | sed "s/\.rb$//")',
        'name="${filename%.rb}"',
    )
    commands = (
        'dist print-upload-files-from-manifest --manifest dist-manifest.json',
        'jq --raw-output ".upload_files[]" dist-manifest.json',
    )
    for command in commands:
        before = (
            '          echo "paths<<EOF" >> "$GITHUB_OUTPUT"\n'
            f'          {command} >> "$GITHUB_OUTPUT"\n'
            '          echo "EOF" >> "$GITHUB_OUTPUT"'
        )
        after = (
            '          {\n'
            '            echo "paths<<EOF"\n'
            f'            {command}\n'
            '            echo "EOF"\n'
            '          } >> "$GITHUB_OUTPUT"'
        )
        text = replace_once(text, before, after)
    return text


def normalize_tags(text: str) -> str:
    text = replace_once(
        text,
        'permissions:\n  "contents": "write"\n',
        'permissions:\n  "contents": "write"\n\nenv:\n'
        "  RELEASE_TAG: ${{ !github.event.pull_request && github.ref_name || '' }}\n",
    )
    text = replace_once(
        text,
        "      tag-flag: ${{ !github.event.pull_request && format('--tag={0}', github.ref_name) || '' }}\n",
        '',
    )
    text = replace_once(
        text,
        "          dist ${{ (!github.event.pull_request && format('host --steps=create --tag={0}', github.ref_name)) || 'plan' }} --output-format=json > plan-dist-manifest.json",
        '          if [ -n "$RELEASE_TAG" ]; then\n'
        '            if [ "${#RELEASE_TAG}" -gt 256 ] || [[ "$RELEASE_TAG" == *[!a-zA-Z0-9._+/-]* ]]; then\n'
        '              echo "Invalid release tag" >&2\n'
        '              exit 1\n'
        '            fi\n'
        '            dist host --steps=create "--tag=$RELEASE_TAG" --output-format=json > plan-dist-manifest.json\n'
        '          else\n'
        '            dist plan --output-format=json > plan-dist-manifest.json\n'
        '          fi',
    )
    text = replace_once(
        text,
        'gh release create "${{ needs.plan.outputs.tag }}"',
        'gh release create "$RELEASE_TAG"',
    )
    return normalize_tag_arguments(text)


def normalize_tag_arguments(text: str) -> str:
    text = replace_once(
        text,
        '      - name: Build artifacts\n        run: |',
        '      - name: Build artifacts\n        shell: bash\n        run: |',
    )
    commands = (
        ('build', '--print=linkage --output-format=json ${{ matrix.dist_args }}'),
        ('build', '--output-format=json "--artifacts=global"'),
        ('host', '--steps=upload --steps=release --output-format=json'),
    )
    for command, arguments in commands:
        before = f'          dist {command} ${{{{ needs.plan.outputs.tag-flag }}}} {arguments}'
        after = (
            '          tag_args=()\n'
            '          if [ -n "$RELEASE_TAG" ]; then tag_args+=("--tag=$RELEASE_TAG"); fi\n'
            f'          dist {command} "${{tag_args[@]}}" {arguments}'
        )
        text = replace_once(text, before, after)
    return text


def normalize(text: str) -> str:
    return normalize_tags(normalize_shell(text))


def read_bounded(filename: Path) -> str:
    with filename.open("rb") as source:
        data = source.read(MAX_WORKFLOW_BYTES + 1)
    if len(data) > MAX_WORKFLOW_BYTES:
        raise ValueError("Dist configuration exceeds its size bound")
    return data.decode("utf-8")


def generate(root: Path, dist: str) -> None:
    config = root / "dist-workspace.toml"
    original = read_bounded(config)
    clean = replace_once(original, 'allow-dirty = ["ci"]\n', '')
    config.write_text(clean, encoding="utf-8")
    try:
        subprocess.run([dist, "generate", "--mode", "ci"], cwd=root, check=True, timeout=60)
    finally:
        if read_bounded(config) != clean:
            raise ValueError("Dist configuration changed concurrently; restore allow-dirty manually")
        config.write_text(original, encoding="utf-8")


def main() -> None:
    if len(sys.argv) > 2:
        raise ValueError("Usage: python3 ci/normalize_dist_workflow.py [DIST_EXECUTABLE]")
    root = Path(__file__).resolve().parents[1]
    generate(root, sys.argv[1] if len(sys.argv) == 2 else "dist")
    workflow = root / ".github/workflows/release.yml"
    normalized = normalize(read_bounded(workflow))
    workflow.write_text(normalized, encoding="utf-8")


if __name__ == "__main__":
    main()
